### ISSUE TITLE
Swap me with alex

### ISSUE THREAD

**Issue by ghost** [ccaa-team/Communist-Christians-Against-Alzeheimer.github.io#5]
She's not part of the GitHub™ organization

**Comment by 9551-Dev** [comment]
> She's not part of the GitHub™ organization

i mean we can just add her

**Comment by ghost** [comment]
> > She's not part of the GitHub™ organization
> i mean we can just add her

but that's the boring soluiton

**Comment by 9551-Dev** [comment]
> > > She's not part of the GitHub™ organization
> > > i mean we can just add her
> 
> but that's the boring soluiton

eh

**Comment by ghost** [comment]
or swap me with alex :tf:
he can't even make a 3d engine

**Comment by VRTULE1775** [comment]
hi :>

**Comment by 9551-Dev** [comment]
> or swap me with alex :tf: he can't even make a 3d engine

fr, smh. Its quite shrimple too.

**Comment by ghost** [comment]
REAL
